### ISSUE TITLE
Instance type for third node group in the AZ-C is missing

### ISSUE THREAD

**Issue by nbmustafa** [marcincuber/eks#2]
Hello Marcin. 
I have been going through your excellent work since yesterday, found that instance type is missing for the third AZ
module "eks-node-group-c" {
https://github.com/marcincuber/eks/blob/master/terraform-aws/manage-node-group.tf#L57

is that a deliberate move to let ng in the third AZ get the default instance type? or that is just been missed out?

**Comment by marcincuber** [comment]
It is not missing, it is just another way to demonstrate that terraform module `https://github.com/umotif-public/terraform-aws-eks-node-group` is working as expected. And as you rightly mentioned it will default to `instance_types = ["t3.medium"]`
