### ISSUE TITLE
Data archive to zip multiple files instead of having it pre-zipped

### ISSUE THREAD

**Issue by nbmustafa** [marcincuber/eks#3]
Hi Marcin, 

back again with few questions, as I am really feeling your work has been one of the very best put there for other DevOps to get their EKS work and running in a better manner. 

I have three question, I would appreciate if you can give some clarification. 

**Question 1/**
node-drainer.tf what is the file in node_drainer folder that we are zipping? 
There are three folders inside node_drainer, each folder has few files in it? Can you kindly give some explanation there?

I want to use terraform to zip the file on the fly instead of having zip file in the repo (for security compliance purposes). 
**for example I want to zip the node_drainer as below:**

data "archive_file" "node-draining_zip" {
type = "zip"
output_path = "${path.module}/node_drainer/???-${sha256(file("${path.module}/node_drainer/???.py"))}.zip"
source_file = "${path.module}/node_drainer/???.py"
}

**then call it like this:**
source_code_hash = data.archive_file.node-draining_zip.output_base64sha256

**Question 2/**
There is a security group you are creating but seems like this hasn’t been used anywhere? 
https://github.com/marcincuber/eks/blob/master/terraform-aws/cluster.tf#L5
Or am I missing something?

**Question 3/**
 for all configs provided in terraform_k8s inclusing configmap aws-auth and cluster_autoscaler, etc. is there any automated process you are using to configure these templates onto the deployed clusters and node_group? 

Thank you very much.

**Comment by marcincuber** [comment]
Hi @nashvan,

I am glad my work is helping other people.

Q1. Lambda function/code provides a means to gracefully terminate nodes in EKS cluster when managed as part of an Amazon EC2 Auto Scaling Group. For example, when you perform rolling update, nodes need to be drained before they get terminated.

The code provides an AWS Lambda function that integrates as an Amazon EC2 Auto Scaling Lifecycle Hook. When called, the Lambda function calls the Kubernetes API to cordon and evict all evictable pods from the node being terminated. It will then wait until all pods have been evicted before the Auto Scaling group continues to terminate the EC2 instance. The lambda may be killed by the function timeout before all evictions complete successfully, in which case the lifecycle hook may re-execute the lambda to try again. If the lifecycle heartbeat expires then termination of the EC2 instance will continue regardless of whether or not draining was successful. You may need to increase the function and heartbeat timeouts in template.yaml if you have very long grace periods.

Using this approach can minimise disruption to the services running in your cluster by allowing Kubernetes to reschedule the pod prior to the instance being terminated enters the TERMINATING state. It works by using Amazon EC2 Auto Scaling Lifecycle Hooks to trigger an AWS Lambda function that uses the Kubernetes API to cordon the node and evict the pods.

Q2. Just to be precise, it is a `aws_security_group_rule`. This one specifically allows EKS to make use of endpoints configured in https://github.com/marcincuber/eks/blob/master/terraform-aws/vpc.tf#L56. VPC endpoints allow for private connectivity with the VPC.

Q3. There are different ways to deploying yaml templates. Personally, I am making use of a tool called Flux (https://github.com/fluxcd/flux). Using flux, you are basically control templates in your git repository and flux will apply them in the cluster.

**Comment by nbmustafa** [comment]
Hello @marcincuber 
thank you very much for the detailed answer, though my first question seems not to have been answered yet, I understand the how this lambda works and why we are using it hear. my question is you have got few .py files inside node_drainer folder. which one is the correct python code been used?

**Comment by marcincuber** [comment]
@nashvan apologies. So the files that are zipped are in `https://github.com/marcincuber/eks/tree/master/terraform-aws/node_drainer/drainer`. I am zipping it into a single zip as it is not going to change anytime soon. So files `handler.py` and
`k8s_utils.py` are the crucial ones.

**Comment by nbmustafa** [comment]
@marcincuber  for somereasons I am not able to use your zip file.

Error installing provider "template": Get https://releases.hashicorp.com/terraform-provider-template/2.1.2/terraform-provider-template_2.1.2_darwin_amd64.zip: net/http: TLS handshake timeout.
Error: unable to verify checksum

that is why I wanted to use

```hcl
data "archive_file" "node-draining_zip" {
type = "zip"
output_path = "${path.module}/node_drainer/???-${sha256(file("${path.module}/node_drainer/???.py"))}.zip"
source_file = "${path.module}/node_drainer/???.py"
}

```
to zip the file. that means I only need handler.py and k8s_utils.py?

**Comment by marcincuber** [comment]
```
pip3 install -r ./node_drainer/drainer/requirements.txt --target ./lambda_build
cp ./node_drainer/drainer/__init__.py ./node_drainer/drainer/handler.py ./node_drainer/drainer/k8s_utils.py ./lambda_build
cd lambda_build && zip -r ../node_drainer.zip ./* && cd .. && rm -rf lambda_build
```
These are commands that I am using locally to build the zip.

**Comment by nbmustafa** [comment]
Thank you very much @marcincuber, I used terraform data archive to zip the files, I just wanted to know which files are the ones needed to be included to the zip file. 

I am curious to know if you have recently run this module
as per your source module:
https://github.com/umotif-public/terraform-aws-eks-node-group/blob/master/main.tf

enabled         = var.enable_managed_workers 
https://github.com/marcincuber/eks/blob/master/terraform-aws/manage-node-group.tf#L5
doesnt seems to be accepted, because there is no such param declared in the source module.

**Comment by marcincuber** [comment]
@nashvan you are absolutely right. I upgraded the module to support terraform 0.13. This means `terraform-aws-eks-node-group` no longer needs enabled variable and therefore it was removed. 

It should be changed to (enabled is removed and terraform 0.13 required):

```
module "eks-node-group" {
  source = "umotif-public/eks-node-group/aws"
  version = "~> 3.0.0"
  count = var.enable_managed_workers ? 1 : 0
  ...
```

[Update] I updated master branch with the updated module configs.

**Comment by nbmustafa** [comment]
Thanks @marcincuber
